name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Python for static code analysis
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: List files for debugging
        run: |
          ls  -R

      - name: Install system dependencies for dbus-python
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libglib2.0-dev
          
      - name: Install system dependencies for cairo
        run: sudo apt-get install -y libcairo2-dev

      - name: Install system dependencies for gobject-introspection
        run: sudo apt-get install -y libgirepository1.0-dev

      - name: Install libsystemd development packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev

      - name: Install system dependencies for pycups
        run: sudo apt-get update && sudo apt-get install -y libcups2-dev
  
      # Install required dependencies for static code analysis
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install --no-cache-dir -v -r app/requirements.txt

      # Run static code analysis with pylint
      - name: Run static code analysis
        run: |
          pylint app/**/*.py

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker Image
      - name: Build the Docker Image
        run: |
          docker build -t todo-app -f app/Dockerfile app

      # Run Trivy to scan the Docker image for vulnerabilities
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image: todo-app
          format: 'table'

          
    
